// SPDX-License-Identifier: MIT
// One host connection owns the wire. Source leaves only in save-request; assets is a separate picture grant.
// ---- BEGIN contract.mjs (generated by tools/sync-embed-contract.mjs; edit contract.mjs) ----
const {FEATURES, LIMITS, ASSET_TYPES, refusal, normalizeSettings, snapshotSettings, assetURL, assetBytes, bytesHash, externalImage, createAssetBroker} = (() => {
// The host's optional policy and picture exchange. No storage, network or editor authority.
const FEATURES = Object.freeze(['draw', 'paint', 'notes', 'readAloud', 'share', 'find']);
const LIMITS = Object.freeze({documentBytes: 25 * 1024 * 1024, pictureBytes: 16 * 1024 * 1024});
const ASSET_TYPES = Object.freeze(['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/jxl', 'image/svg+xml']);
const ACCENTS = Object.freeze(['Teal', 'Blue', 'Amber', 'Green', 'Red', 'Purple', 'Pink', 'Gray']);
const refusal = (code, reason = code) => Object.assign(new Error(reason), {code});
const record = value => value !== null && typeof value === 'object' && !Array.isArray(value) &&
  (Object.getPrototypeOf(value) === null || Object.getPrototypeOf(Object.getPrototypeOf(value)) === null);
const only = (value, keys) => Object.keys(value).every(key => keys.includes(key));

function normalizeSettings(value = {}, {features = FEATURES, accents = ACCENTS, languages = ['en'], limits = LIMITS} = {}) {
  if (!record(value)) throw refusal('settings_invalid');
  if (!only(value, ['features', 'language', 'limits', 'palette'])) throw refusal('settings_unknown');
  let selected = features;
  if (value.features !== undefined) {
    if (!Array.isArray(value.features) || value.features.length > FEATURES.length ||
        new Set(value.features).size !== value.features.length) throw refusal('settings_features_invalid');
    if (value.features.some(name => !FEATURES.includes(name))) throw refusal('settings_feature_unknown');
    selected = features.filter(name => value.features.includes(name));
  }
  let language = languages[0];
  if (value.language !== undefined) {
    if (typeof value.language !== 'string' || !value.language || value.language.length > 63) throw refusal('settings_language_invalid');
    let canonical;
    try { canonical = Intl.getCanonicalLocales(value.language)[0]; }
    catch (_) { throw refusal('settings_language_invalid'); }
    language = languages.find(tag => tag.toLowerCase() === canonical.toLowerCase()) || languages[0];
  }
  const acceptedLimits = {...limits};
  if (value.limits !== undefined) {
    if (!record(value.limits) || !only(value.limits, Object.keys(LIMITS))) throw refusal('settings_limits_invalid');
    for (const [key, bytes] of Object.entries(value.limits)) {
      if (!Number.isSafeInteger(bytes) || bytes < 1) throw refusal('settings_limits_invalid');
      acceptedLimits[key] = Math.min(bytes, limits[key]);
    }
  }
  let palette;
  if (value.palette !== undefined) {
    if (!record(value.palette) || !only(value.palette, ['accent']) || !accents.includes(value.palette.accent))
      throw refusal('settings_palette_invalid');
    palette = Object.freeze({accent: value.palette.accent});
  }
  return Object.freeze({features: Object.freeze([...selected]), language, limits: Object.freeze(acceptedLimits),
    ...(palette ? {palette} : {})});
}

// Take only the fields the host offered: absent features still mean whatever that build carries.
function snapshotSettings(value) {
  if (value === undefined) return undefined;
  const accepted = normalizeSettings(value);
  return Object.freeze(Object.fromEntries(Object.keys(value).map(key => [key, accepted[key]])));
}

function assetURL(value) {
  if (typeof value !== 'string' || !value || value.length > 4096 || /[\s\u0000-\u001f\u007f<>\\]/u.test(value))
    throw refusal('asset_url_invalid');
  let url;
  try { url = new URL(value); } catch (_) { throw refusal('asset_url_invalid'); }
  if (url.protocol !== 'https:' || url.username || url.password || url.href.length > 4096) throw refusal('asset_url_invalid');
  return url.href;
}

function assetBytes(value, limit = LIMITS.pictureBytes) {
  if (!(value instanceof Uint8Array) || !value.byteLength) throw refusal('asset_bytes_invalid');
  if (value.byteLength > Math.min(limit, LIMITS.pictureBytes)) throw refusal('picture_too_large');
  return value;
}
async function bytesHash(bytes) {
  return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)), n => n.toString(16).padStart(2, '0')).join('');
}
function externalImage(raw, asset, url) {
  if (!url) return raw;
  const token = '[' + asset.label + ']', at = raw.lastIndexOf(token);
  if (at < 0) throw refusal('asset_reference_invalid');
  const title = asset.title ? ' "' + String(asset.title).replace(/&/g, '&amp;').replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/[\r\n]/g, ' ') + '"' : '';
  return raw.slice(0, at) + '(<' + assetURL(url).replace(/&/g, '&amp;') + '>' + title + ')' + raw.slice(at + token.length);
}

// At most one upload is in flight. A failure returns the embedded form, never a deletion.
// Retained local pictures are bounded separately from the host's (possibly tiny) document limit.
function createAssetBroker({current, send}) {
  const retained = new Map();
  let pending = null, identity = '', retainedBytes = 0;
  const same = (a, b) => a.identity === b.identity && a.generation === b.generation && b.connected && b.granted;
  function scope() {
    const now = current();
    if (identity !== now.identity) { retained.clear(); retainedBytes = 0; identity = now.identity; }
    return now;
  }
  function cancel(code = 'asset_disconnected') { pending?.finish({code}); }
  async function request(asset) {
    const state = scope(), bytes = assetBytes(asset.bytes, state.pictureBytes);
    if (!state.granted) return {code: 'asset_not_granted'};
    if (!state.connected) return {code: 'asset_disconnected'};
    if (pending) return {code: 'asset_busy'};
    if (!ASSET_TYPES.includes(asset.codec)) throw refusal('asset_media_type_invalid');
    if (retained.size >= 1024 || retainedBytes + bytes.byteLength > LIMITS.documentBytes) return {code: 'asset_cache_full'};
    // Keep our own bytes: postMessage clones them, never transfers/detaches the kept picture.
    const kept = {...asset, bytes: bytes.slice()};
    let resolve;
    const job = new Promise(yes => { resolve = yes; });
    const row = {state, asset: kept, requestId: crypto.randomUUID(), timer: null, bytesSha256: '',
      finish(value) {
        if (pending !== row) return;
        clearTimeout(row.timer); pending = null; resolve(value);
      }};
    pending = row;
    row.timer = setTimeout(() => row.finish({code: 'asset_timeout'}), 15000);
    bytesHash(kept.bytes).then(hash => {
      if (pending !== row) return;
      if (!same(state, scope())) { row.finish({code: 'asset_stale'}); return; }
      row.bytesSha256 = hash;
      if (!send('asset-request', {bytesSha256: hash, mediaType: kept.codec, bytes: kept.bytes}, row.requestId, state.baseRevision))
        row.finish({code: 'asset_unavailable'});
    }).catch(() => row.finish({code: 'asset_unavailable'}));
    return job;
  }
  function answer(message) {
    const row = pending;
    if (!row || message.requestId !== row.requestId || message.baseRevision !== row.state.baseRevision)
      return {code: 'asset_unmatched'};
    let result;
    if (!same(row.state, scope())) result = {code: 'asset_stale'};
    else if (message.type === 'asset-nack') result = {code: 'asset_rejected'};
    else if (message.type !== 'asset-ack') result = {code: 'asset_reply_invalid'};
    else {
      try {
        const url = assetURL(message.payload?.url), prior = retained.get(url);
        if (prior && (prior.bytesSha256 !== row.bytesSha256 || prior.asset.codec !== row.asset.codec)) result = {code: 'asset_url_conflict'};
        else {
          if (!prior) { retained.set(url, {asset: row.asset, bytesSha256: row.bytesSha256}); retainedBytes += row.asset.bytes.byteLength; }
          result = {url};
        }
      } catch (error) { result = {code: error.code || 'asset_url_invalid'}; }
    }
    row.finish(result);
    return result;
  }
  function lookup(url) { scope(); return retained.get(url)?.asset || null; }
  return Object.freeze({request, answer, cancel, lookup});
}
return {FEATURES, LIMITS, ASSET_TYPES, refusal, normalizeSettings, snapshotSettings, assetURL, assetBytes, bytesHash, externalImage, createAssetBroker};
})();
// ---- END contract.mjs ----
const DEFAULT_SRC = 'https://rapier.website/embed/rapier-document.html';
const revision = value => Number.isSafeInteger(value) && value >= 0 || typeof value === 'string' && value.length > 0 && value.length <= 256;
const identifier = value => typeof value === 'string' && value.length > 0 && value.length <= 256;
const record = value => value !== null && typeof value === 'object' && !Array.isArray(value);
const themeValue = value => ['light', 'dark', 'system'].includes(value);
const mint = prefix => prefix + '-' + (globalThis.crypto?.randomUUID?.() || Math.random().toString(36).slice(2));
function deferred() {
  let resolve, reject;
  const promise = new Promise((yes, no) => { resolve = yes; reject = no; });
  // A handle can be mounted before its caller starts awaiting it.
  promise.catch(() => {});
  return {promise, resolve, reject};
}
const refused = payload => Object.assign(new Error(payload?.reason || payload?.code || 'The editor refused the request'), {code: payload?.code, payload});

function conflict(currentRevision) {
  if (!revision(currentRevision)) throw new TypeError('A conflict needs the current revision');
  return Object.assign(new Error('The stored document has changed'), {code: 'conflict', currentRevision});
}

function mount(target, options = {}) {
  const document = target?.ownerDocument;
  if (!document) throw new TypeError('Mount needs an iframe or a container element');
  const host = document.defaultView, iframe = target.tagName === 'IFRAME' ? target : document.createElement('iframe');
  const source = new URL(options.src || DEFAULT_SRC, host.location.href);
  if (source.username || source.password || !(source.protocol === 'https:' || source.protocol === 'http:' && ['localhost', '127.0.0.1', '[::1]'].includes(source.hostname)))
    throw new TypeError('The editor needs HTTPS, or HTTP on localhost');
  source.searchParams.set('embed', '1');
  const origin = source.origin, sessionId = options.sessionId ?? mint('session'), documentId = options.documentId ?? mint('document');
  if (!identifier(sessionId) || !identifier(documentId)) throw new TypeError('Session and document IDs must be nonempty strings of at most 256 code units');
  if (options.theme !== undefined && !themeValue(options.theme)) throw new TypeError('Theme must be light, dark or system');
  if (options.save !== undefined && typeof options.save !== 'function') throw new TypeError('save must be a durable storage callback');
  if (options.assets !== undefined && typeof options.assets !== 'function') throw new TypeError('assets must be a picture storage callback');
  const settings = snapshotSettings(options.settings), policy = normalizeSettings(settings), storeAsset = options.assets;
  const assetAnswers = new Map();
  let assetPending = '', assetAbort = new AbortController();
  const capabilities = [
    ...(options.load !== undefined ? ['open'] : []), ...(options.save ? ['read'] : []),
    ...(options.save || options.onState ? ['changes'] : []), ...(options.compare ? ['compare'] : []),
    ...(options.onClose ? ['close'] : []), ...(options.agent ? ['agent'] : []), ...(storeAsset ? ['assets'] : []),
  ];
  if (options.agent && (!capabilities.includes('open') || !capabilities.includes('read')))
    throw new TypeError('Agent access needs both load and save');
  const ids = {sessionId, documentId}, answers = new Map(), waiting = new Map(), listeners = new Map();
  let port = null, posted = false, connected = false, ended = false, sawLoad = false, seq = 0, activeSave = null, activeClose = null;
  let currentTheme = options.theme, lastSaved = null, readOnly = false, connectedWait = deferred(), boot;
  const ready = deferred();
  const emit = (type, value) => { for (const fn of listeners.get(type) || []) fn(value); };
  const fail = error => { emit('error', error); options.onError?.(error); };
  const rejectPending = error => {
    for (const job of waiting.values()) job.reject(error);
    waiting.clear(); activeSave?.reject(error); activeSave = null; activeClose?.reject(error); activeClose = null;
  };
  function send(type, payload, baseRevision, quiet = false) {
    if (ended || !connected || !port) return Promise.reject(new Error('The editor connection has ended or is not connected'));
    const requestId = 'host-' + ++seq;
    const message = {type, ...ids, requestId, ...(baseRevision !== undefined ? {baseRevision} : {}), ...(payload !== undefined ? {payload} : {})};
    const pending = deferred();
    if (!quiet) waiting.set(requestId, pending);
    try { port.postMessage(message); if (quiet) pending.resolve(); }
    catch (error) { waiting.delete(requestId); pending.reject(error); }
    return pending.promise;
  }
  function requestCapture() {
    send('save', undefined, undefined, true).catch(error => { activeSave?.reject(error); activeSave = null; });
  }
  async function answerSave(message, channel) {
    const {requestId, baseRevision, payload} = message;
    if (!options.save || !identifier(requestId) || !revision(baseRevision) || typeof payload?.content !== 'string') return;
    if (!answers.has(requestId)) {
      // Cache the promise before entering storage: an in-flight Retry is the same write.
      const job = Promise.resolve().then(async () => {
        try {
          const result = await options.save({...payload, requestId, baseRevision});
          if (!revision(result?.revision) || result.revision === baseRevision || typeof result.revision === 'number' && typeof baseRevision === 'number' && result.revision <= baseRevision)
            throw new TypeError('save must return an advancing durable revision');
          return {type: 'save-ack', ...ids, requestId, baseRevision, payload: {revision: result.revision}};
        } catch (error) {
          return {type: 'save-nack', ...ids, requestId, baseRevision, payload: error?.code === 'conflict' && revision(error.currentRevision)
            ? {code: 'conflict', currentRevision: error.currentRevision}
            : {code: 'failed', reason: String(error?.message || error).slice(0, 500)}};
        }
      });
      answers.set(requestId, job);
    }
    const reply = await answers.get(requestId);
    if (ended || channel !== port) return;
    channel.postMessage(reply);
    if (reply.type === 'save-ack') {
      lastSaved = reply.payload;
      if (activeSave) activeSave.acknowledged = true;
    } else if (activeSave) { activeSave.reject(refused(reply.payload)); activeSave = null; }
  }
  async function answerAsset(message, channel) {
    const {requestId, baseRevision, payload} = message;
    if (!storeAsset || !identifier(requestId)) return;
    const reply = (type, result) => {
      if (!ended && channel === port) channel.postMessage({type, ...ids, requestId, baseRevision, payload: result});
    };
    try {
      if (Object.keys(payload).some(key => !['bytes', 'bytesSha256', 'mediaType'].includes(key)) ||
          !ASSET_TYPES.includes(payload.mediaType) || typeof payload.bytesSha256 !== 'string' || !/^[a-f0-9]{64}$/.test(payload.bytesSha256))
        throw refusal('asset_payload_invalid');
      const bytes = assetBytes(payload.bytes, policy.limits.pictureBytes);
      const signature = JSON.stringify([baseRevision, payload.bytesSha256, payload.mediaType, bytes.byteLength]);
      let row = assetAnswers.get(requestId);
      if (row && row.signature !== signature) throw refusal('asset_request_conflict');
      if (!row) {
        if (assetPending) throw refusal('asset_busy');
        if (assetAnswers.size >= 48) assetAnswers.delete(assetAnswers.keys().next().value);
        const signal = assetAbort.signal;
        row = {signature, job: null}; assetAnswers.set(requestId, row); assetPending = requestId;
        row.job = Promise.resolve().then(async () => {
          try {
            if (await bytesHash(bytes) !== payload.bytesSha256) throw refusal('asset_hash_mismatch');
            signal.throwIfAborted();
            const result = await storeAsset({requestId, bytesSha256: payload.bytesSha256, mediaType: payload.mediaType, bytes, signal});
            signal.throwIfAborted();
            return {type: 'asset-ack', payload: {url: assetURL(result?.url)}};
          } catch (error) {
            return {type: 'asset-nack', payload: {code: typeof error?.code === 'string' && error.code.length > 0 && error.code.length <= 64 ? error.code : 'asset_failed',
              reason: String(error?.message || error).slice(0, 500)}};
          } finally { if (assetPending === requestId) assetPending = ''; }
        });
      } else if (await bytesHash(bytes) !== payload.bytesSha256) throw refusal('asset_hash_mismatch');
      const answer = await row.job;
      reply(answer.type, answer.payload);
    } catch (error) {
      reply('asset-nack', {code: error.code || 'asset_failed', reason: String(error.message || error).slice(0, 500)});
    }
  }
  function onPortMessage(event, channel) {
    if (channel !== port || ended) return;
    const message = event.data;
    if (!record(message) || message.sessionId !== sessionId || message.documentId !== documentId || !record(message.payload)
      || !(message.requestId === null || identifier(message.requestId)) || !(message.baseRevision == null || revision(message.baseRevision))) return;
    const {type, payload, requestId} = message, pending = waiting.get(requestId);
    if (type === 'protocol-error' && !connected) {
      const error = refused(payload); connectedWait.reject(error); ready.reject(error); fail(error); return;
    }
    if (type === 'connected') {
      if (connected) return;
      connected = true; connectedWait.resolve(); emit('connected', payload); return;
    }
    if (!connected) return;
    if (type === 'asset-request') { answerAsset(message, channel).catch(fail); return; }
    if (type === 'save-request') { answerSave(message, channel).catch(fail); return; }
    if (type === 'document-state' && capabilities.includes('changes')) {
      if (!['loaded', 'dirty', 'saving', 'closing', 'readOnly'].every(key => typeof payload[key] === 'boolean')
        || Object.keys(payload).some(key => !['loaded', 'dirty', 'saving', 'closing', 'readOnly', 'filename', 'docKind'].includes(key))) return;
      readOnly = payload.readOnly; emit('state', payload); options.onState?.(payload);
      // Storage completion alone cannot settle Save: the frame may hold newer edits or an earlier save.
      if (activeSave?.acknowledged && !payload.saving && message.baseRevision === lastSaved?.revision) {
        if (payload.dirty) { activeSave.acknowledged = false; requestCapture(); }
        else { activeSave.resolve(lastSaved); activeSave = null; }
      }
      return;
    }
    if (type === 'agent-review' && options.agent) { emit('agent-review', payload); return; }
    if (type === 'close-request' && options.onClose) {
      Promise.resolve().then(() => options.onClose({dirty: !!payload.dirty})).then(decision => {
        if (!['save', 'discard', 'cancel'].includes(decision)) throw new TypeError('Close needs save, discard or cancel');
        if (channel !== port || ended) return;
        channel.postMessage({type: 'close-decision', ...ids, requestId, baseRevision: message.baseRevision, payload: {decision}});
        if (decision === 'cancel') { activeClose?.resolve({cancelled: true}); activeClose = null; }
      }).catch(error => { activeClose?.reject(error); activeClose = null; fail(error); });
      emit('close-request', payload); return;
    }
    if (type === 'close-ready' && options.onClose) { activeClose?.resolve(payload); activeClose = null; emit('closed', payload); return; }
    if (type === 'protocol-error') {
      const error = refused(payload);
      // Picture storage has its own outcome; its fallback cannot reject an unrelated durable save.
      if (typeof payload.code === 'string' && payload.code.startsWith('asset_')) { fail(error); return; }
      if (pending) { waiting.delete(requestId); pending.reject(error); }
      else { activeSave?.reject(error); activeSave = null; activeClose?.reject(error); activeClose = null; fail(error); }
      return;
    }
    if (pending && ['load-ack', 'load-nack', 'compare-ack', 'compare-nack'].includes(type)) {
      waiting.delete(requestId);
      if (type === 'load-ack') readOnly = payload.readOnly === true;
      if (type.endsWith('-nack')) pending.reject(refused(payload)); else pending.resolve(payload);
    }
  }
  function prepareBoot() {
    boot = connectedWait.promise.then(async () => {
      if (options.load !== undefined) {
        const value = typeof options.load === 'function' ? await options.load() : options.load;
        if (!record(value) || typeof value.content !== 'string' || !revision(value.revision)) throw new TypeError('load needs content and its revision');
        await send('load', value, null);
      }
      ready.resolve(handle);
    });
    boot.catch(error => { ready.reject(error); if (!ended) fail(error); });
  }
  function connect() {
    if (posted || ended) return;
    const channel = new host.MessageChannel();
    port = channel.port1; posted = true;
    port.onmessage = event => onPortMessage(event, channel.port1);
    port.onmessageerror = () => { assetAbort.abort(); rejectPending(new Error('The editor connection was lost')); };
    try { iframe.contentWindow.postMessage({type: 'rapier-connect', ...ids, capabilities, contract: 1, ...(settings ? {settings} : {}), ...(currentTheme ? {theme: currentTheme} : {})}, origin, [channel.port2]); }
    catch (error) { port.close(); port = null; posted = false; fail(error); }
  }
  function onLoad() {
    if (sawLoad && posted) {
      rejectPending(new Error('The editor reconnected')); port?.close();
      assetAbort.abort(refusal('asset_disconnected')); assetAbort = new AbortController();
      connected = false; posted = false; readOnly = false; connectedWait = deferred(); prepareBoot();
    }
    sawLoad = true;
    connect();
  }
  function onWindowMessage(event) {
    if (event.source !== iframe.contentWindow || event.origin !== origin) return;
    if (event.data?.type === 'rapier-ready') connect();
    else if (event.data?.type === 'close-ready' && event.data.sessionId === sessionId && event.data.documentId === documentId && options.onClose) {
      activeClose?.resolve(event.data.payload); activeClose = null; emit('closed', event.data.payload);
    }
  }
  const handle = Object.freeze({
    iframe, ready: ready.promise,
    get connected() { return connected && !ended; },
    async load(content, {filename, revision: version, readOnly, title} = {}) {
      await boot;
      return send('load', {content, revision: version, ...(filename !== undefined ? {filename} : {}), ...(readOnly !== undefined ? {readOnly} : {}), ...(title !== undefined ? {title} : {})}, null);
    },
    async save() {
      await boot;
      if (!options.save) throw new Error('No save callback was granted');
      if (ended) throw new Error('The editor connection has ended');
      if (readOnly) throw new Error('The document is read-only');
      if (!activeSave) activeSave = {...deferred(), acknowledged: false};
      const promise = activeSave.promise;
      requestCapture(); return promise;
    },
    async compare(content, {filename} = {}) { await boot; return send('compare', {content, ...(filename !== undefined ? {filename} : {})}); },
    async close() {
      await boot;
      if (!options.onClose) throw new Error('No close callback was granted');
      if (!activeClose) { activeClose = deferred(); send('close', undefined, undefined, true).catch(error => { activeClose?.reject(error); activeClose = null; }); }
      return activeClose.promise;
    },
    async theme(value) {
      if (!themeValue(value)) throw new TypeError('Theme must be light, dark or system');
      currentTheme = value; await boot; return send('theme', {theme: value}, undefined, true);
    },
    disconnect() {
      if (ended) return;
      if (connected) send('disconnect', undefined, undefined, true).catch(() => {});
      ended = true; connected = false;
      assetAbort.abort(refusal('asset_disconnected')); assetAnswers.clear();
      const error = new Error('The editor connection has ended');
      rejectPending(error); connectedWait.reject(error); ready.reject(error);
      host.removeEventListener('message', onWindowMessage); iframe.removeEventListener('load', onLoad);
      port?.close(); port = null; listeners.clear();
    },
    on(type, fn) {
      if (typeof fn !== 'function') throw new TypeError('An event listener must be a function');
      if (!listeners.has(type)) listeners.set(type, new Set()); listeners.get(type).add(fn);
      return () => listeners.get(type)?.delete(fn);
    },
  });
  prepareBoot();
  iframe.setAttribute('title', options.title || 'Markdown editor');
  iframe.setAttribute('allow', options.agent ? 'clipboard-write; tools' : 'clipboard-write');
  iframe.setAttribute('sandbox', 'allow-scripts allow-same-origin allow-downloads');
  // Install before navigation or insertion: the first ready or load can arrive immediately.
  host.addEventListener('message', onWindowMessage); iframe.addEventListener('load', onLoad);
  iframe.src = source.href;
  if (iframe !== target) target.append(iframe);
  return handle;
}

export const Rapier = Object.freeze({mount, conflict});

// One submit owner per form captures every enabled editor before native validation and submission.
const forms = new WeakMap();
function joinForm(field, form) {
  if (!form) return () => {};
  let group = forms.get(form);
  if (!group) {
    group = {fields: new Set(), pending: false, releasing: false};
    group.submit = async event => {
      if (group.releasing) return;
      event.preventDefault();
      if (group.pending) return;
      group.pending = true;
      const submitter = event.submitter;
      const enabled = () => [...group.fields].filter(field => field.isConnected && field.form === form && !field._disabled);
      const captured = enabled().map(field => ({field, generation: field._generation, authority: field._formAuthority}));
      // A reset, replacement or association change retires this submit, including a rejected old capture.
      const current = () => forms.get(form) === group && enabled().length === captured.length && captured.every(({field, generation, authority}) =>
        group.fields.has(field) && field.isConnected && field.form === form && !field._disabled && field._generation === generation && field._formAuthority === authority);
      try {
        await Promise.all(captured.map(({field}) => field.save()));
        if (!current() || submitter && (submitter.form !== form || submitter.disabled)) return;
        group.releasing = true;
        // requestSubmit repeats native constraints, submitter overrides and all ordinary submit listeners.
        if (submitter?.form === form) form.requestSubmit(submitter); else form.requestSubmit();
      } catch (error) { if (current()) for (const {field} of captured) field._error(error); }
      finally { group.pending = false; group.releasing = false; }
    };
    form.addEventListener('submit', group.submit, true); forms.set(form, group);
  }
  group.fields.add(field);
  return () => {
    group.fields.delete(field);
    if (!group.fields.size) { form.removeEventListener('submit', group.submit, true); forms.delete(form); }
  };
}

export class RapierEditor extends (globalThis.HTMLElement || class {}) {
  static formAssociated = true;
  static observedAttributes = ['disabled', 'required', 'theme', 'src', 'name'];
  constructor() {
    super();
    this._internals = this.attachInternals(); this._value = ''; this._revision = 0; this._dirty = false;
    this._disabled = false; this._initialized = false; this._sync = Promise.resolve(); this._generation = 0; this._formAuthority = 0;
    const shadow = this.attachShadow({mode: 'open', delegatesFocus: true}), doc = this.ownerDocument;
    const style = doc.createElement('style');
    style.textContent = ':host{display:block}button{font:inherit;color:inherit;cursor:pointer}.preview{width:100%;white-space:pre-wrap;text-align:start;padding:1rem;max-height:16rem;overflow:auto}.panel{box-sizing:border-box;width:100%;height:32rem;border:0;padding:0;position:static;color:inherit;background:Canvas}.mount,.mount iframe{width:100%;height:100%;border:0}.done{display:none}@media(max-width:600px){.panel{position:fixed;inset:0;width:100%;max-width:none;height:100dvh;max-height:none;margin:0}.mount{height:calc(100% - 3rem)}.done{display:block;height:3rem;width:100%}}@media(min-width:601px){.preview{display:none}}';
    this._preview = doc.createElement('button'); this._preview.type = 'button'; this._preview.className = 'preview';
    this._panel = doc.createElement('dialog'); this._panel.className = 'panel';
    this._done = doc.createElement('button'); this._done.type = 'button'; this._done.className = 'done'; this._done.textContent = 'Done';
    this._mount = doc.createElement('div'); this._mount.className = 'mount';
    this._panel.append(this._done, this._mount); shadow.append(style, this._preview, this._panel);
    this._preview.addEventListener('click', () => this.focus());
    this._done.addEventListener('click', () => this._finish());
    this._panel.addEventListener('cancel', event => { event.preventDefault(); this._finish(); });
  }
  connectedCallback() {
    if (!this._initialized) {
      this._fallback = this.querySelector('textarea');
      const own = Object.prototype.hasOwnProperty.call(this, 'value') ? this.value : undefined;
      if (own !== undefined) delete this.value;
      this._value = own !== undefined ? String(own) : this._hasValue ? this._value : this._fallback?.value ?? this.textContent;
      this._defaultValue = this._fallback?.defaultValue ?? this._value;
      if (this._fallback) this._fallback.disabled = true;
      this._initialized = true;
    }
    this._disabled = this.matches(':disabled'); this.tabIndex = this._disabled ? -1 : 0;
    this._media ||= this.ownerDocument.defaultView.matchMedia('(max-width:600px)');
    this._onMedia ||= () => this._layout(); this._media.addEventListener('change', this._onMedia);
    this._bindForm(); this._updateValue(); this._layout(); if (this._panel.open) this._start();
  }
  disconnectedCallback() {
    this._formAuthority++;
    queueMicrotask(() => {
      if (this.isConnected) return;
      this._leaveForm?.(); this._leaveForm = null; this._media?.removeEventListener('change', this._onMedia);
      this._editor?.disconnect(); this._editor = null; this._mount.replaceChildren();
    });
  }
  attributeChangedCallback(name) {
    if (!this._initialized) return;
    if (name === 'disabled') this.formDisabledCallback(this.matches(':disabled'));
    else if (name === 'theme') this._editor?.theme(this.getAttribute('theme') || 'system').catch(error => this._error(error));
    else if (name === 'src') this.save().then(() => this._replace(this._value)).catch(error => this._error(error));
    else this._updateValue();
  }
  get value() { return this._value; }
  set value(value) { this._hasValue = true; this._replace(String(value)); }
  get name() { return this.getAttribute('name') || ''; }
  set name(value) { this.setAttribute('name', value); }
  get disabled() { return this.hasAttribute('disabled'); }
  set disabled(value) { this.toggleAttribute('disabled', !!value); }
  get required() { return this.hasAttribute('required'); }
  set required(value) { this.toggleAttribute('required', !!value); }
  get form() { return this._internals.form; }
  get labels() { return this._internals.labels; }
  get validity() { return this._internals.validity; }
  get validationMessage() { return this._internals.validationMessage; }
  get willValidate() { return this._internals.willValidate; }
  checkValidity() { return this._internals.checkValidity(); }
  reportValidity() { return this._internals.reportValidity(); }
  setCustomValidity(message) { this._customValidity = String(message); this._updateValue(); }
  _bindForm() { this._formAuthority++; this._leaveForm?.(); this._leaveForm = joinForm(this, this.form); }
  formAssociatedCallback() { if (this._initialized && this.isConnected) this._bindForm(); }
  formResetCallback() { this._replace(this._defaultValue); }
  formStateRestoreCallback(state) { if (typeof state === 'string') this._replace(state); }
  formDisabledCallback(disabled) {
    const wasDisabled = this._disabled; this._disabled = disabled;
    if (disabled !== wasDisabled) this._formAuthority++;
    this.tabIndex = disabled ? -1 : 0; this._preview.disabled = disabled; this._mount.inert = disabled;
    if (!this._initialized) return;
    this._updateValue();
    const editor = this._editor;
    if (!editor || disabled === wasDisabled) return;
    this._sync = this._sync.then(async () => {
      if (this._editor !== editor) return;
      await editor.ready;
      if (!wasDisabled) await editor.save();
      if (this._editor === editor) await editor.load(this._value, {filename: this._filename(), revision: this._revision, readOnly: disabled});
    }).catch(error => { if (this._editor === editor) this._error(error); });
  }
  _filename() { return (this.getAttribute('name') || 'document').slice(0, 240) + '.md'; }
  _updateValue() {
    // Multipart text fields normalize newlines. A Markdown file part preserves the exact UTF-8 bytes.
    const File = this.ownerDocument.defaultView.File;
    this._internals.setFormValue(new File([this._value], this._filename(), {type: 'text/markdown'}), this._value);
    this._preview.textContent = this._value || 'Edit document'; this._preview.disabled = this._disabled;
    if (this._fallback) this._fallback.value = this._value;
    const missing = this.required && !this._value && !this._dirty;
    const error = this._customValidity || (missing ? 'Please fill out this field.' : '');
    this._internals.setValidity(error ? (this._customValidity ? {customError: true} : {valueMissing: true}) : {}, error, this._preview);
  }
  _replace(value) {
    this._value = value; this._dirty = false; this._revision = 0; this._generation++;
    this._editor?.disconnect(); this._editor = null; this._mount.replaceChildren(); this._updateValue();
    if (this._initialized && this.isConnected && this._panel.open) this._start();
  }
  _start() {
    if (this._editor) return;
    const generation = this._generation;
    this._editor = Rapier.mount(this._mount, {
      src: this.getAttribute('src') || DEFAULT_SRC, theme: this.getAttribute('theme') || 'system',
      load: {content: this._value, filename: this._filename(), revision: this._revision, readOnly: this._disabled},
      save: ({content, baseRevision}) => {
        if (this._generation !== generation) throw new Error('The form field was replaced');
        if (baseRevision !== this._revision) throw conflict(this._revision);
        this._value = content; this._revision++; this._dirty = false; this._updateValue();
        this.dispatchEvent(new Event('change', {bubbles: true, composed: true}));
        return {revision: this._revision};
      },
      onState: state => { this._dirty = state.dirty; this._updateValue(); },
      onError: error => this._error(error),
    });
    this._mount.inert = this._disabled;
  }
  _layout() {
    const narrow = this._media.matches;
    if (this._narrow === narrow) return;
    this._narrow = narrow;
    if (this._panel.open) this._panel.close();
    if (!narrow) { this._panel.setAttribute('open', ''); this._start(); }
  }
  focus(options) {
    if (this._disabled) return;
    if (this._narrow && !this._panel.open) this._panel.showModal();
    this._start(); this._editor.iframe.focus(options);
  }
  async save() {
    await this._sync;
    if (this._editor && !this._disabled) await this._editor.save();
    return this._value;
  }
  async _finish() {
    try { await this.save(); this._panel.close(); this._preview.focus(); }
    catch (error) { this._error(error); }
  }
  _error(error) { this.dispatchEvent(new CustomEvent('error', {detail: error, bubbles: true, composed: true})); }
}

export function defineRapierEditor(registry = globalThis.customElements) {
  if (!registry || !globalThis.ElementInternals) throw new Error('rapier-editor needs form-associated custom elements');
  if (!registry.get('rapier-editor')) registry.define('rapier-editor', RapierEditor);
  return RapierEditor;
}
